// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuaPeleBackend.Data;

#nullable disable

namespace suapelebackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PacienteProfissionalDeSaude", b =>
                {
                    b.Property<int>("PacientesId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfissionaisDeSaudeId")
                        .HasColumnType("integer");

                    b.HasKey("PacientesId", "ProfissionaisDeSaudeId");

                    b.HasIndex("ProfissionaisDeSaudeId");

                    b.ToTable("PacienteMedicos", (string)null);
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCaptura")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LesaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LesaoId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Lembrete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("DiasSemana")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("interval");

                    b.Property<int?>("LesaoId")
                        .HasColumnType("integer");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TratamentoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LesaoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TratamentoId");

                    b.ToTable("Lembretes");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Lesao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DescricaoTextual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("RegiaoCorpo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Lesoes");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstrucoesEspecificas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TratamentoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TratamentoId");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.PreDiagnostico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAnalise")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LesaoId")
                        .HasColumnType("integer");

                    b.Property<float>("Probabilidade")
                        .HasColumnType("real");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultadoIA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LesaoId");

                    b.ToTable("PreDiagnosticos");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.ProfissionalDeSaude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Dermatologista")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CRM")
                        .IsUnique();

                    b.ToTable("ProfissionaisDeSaude");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Tratamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LesaoId")
                        .HasColumnType("integer");

                    b.Property<string>("ObservacoesGerais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreDiagnosticoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfissionalDeSaudeId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LesaoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("PreDiagnosticoId");

                    b.HasIndex("ProfissionalDeSaudeId");

                    b.ToTable("Tratamentos");
                });

            modelBuilder.Entity("PacienteProfissionalDeSaude", b =>
                {
                    b.HasOne("SuaPeleBackend.Models.Paciente", null)
                        .WithMany()
                        .HasForeignKey("PacientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuaPeleBackend.Models.ProfissionalDeSaude", null)
                        .WithMany()
                        .HasForeignKey("ProfissionaisDeSaudeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Foto", b =>
                {
                    b.HasOne("SuaPeleBackend.Models.Lesao", "Lesao")
                        .WithMany("Fotos")
                        .HasForeignKey("LesaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesao");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Lembrete", b =>
                {
                    b.HasOne("SuaPeleBackend.Models.Lesao", "Lesao")
                        .WithMany()
                        .HasForeignKey("LesaoId");

                    b.HasOne("SuaPeleBackend.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuaPeleBackend.Models.Tratamento", "Tratamento")
                        .WithMany()
                        .HasForeignKey("TratamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesao");

                    b.Navigation("Paciente");

                    b.Navigation("Tratamento");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Lesao", b =>
                {
                    b.HasOne("SuaPeleBackend.Models.Paciente", "Paciente")
                        .WithMany("Lesoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Medicamento", b =>
                {
                    b.HasOne("SuaPeleBackend.Models.Tratamento", "Tratamento")
                        .WithMany("Medicamentos")
                        .HasForeignKey("TratamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamento");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.PreDiagnostico", b =>
                {
                    b.HasOne("SuaPeleBackend.Models.Lesao", "Lesao")
                        .WithMany("PreDiagnosticos")
                        .HasForeignKey("LesaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesao");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Tratamento", b =>
                {
                    b.HasOne("SuaPeleBackend.Models.Lesao", "Lesao")
                        .WithMany()
                        .HasForeignKey("LesaoId");

                    b.HasOne("SuaPeleBackend.Models.Paciente", "Paciente")
                        .WithMany("Tratamentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuaPeleBackend.Models.PreDiagnostico", "PreDiagnosticoOrigem")
                        .WithMany()
                        .HasForeignKey("PreDiagnosticoId");

                    b.HasOne("SuaPeleBackend.Models.ProfissionalDeSaude", "MedicoResponsavel")
                        .WithMany("Tratamentos")
                        .HasForeignKey("ProfissionalDeSaudeId");

                    b.Navigation("Lesao");

                    b.Navigation("MedicoResponsavel");

                    b.Navigation("Paciente");

                    b.Navigation("PreDiagnosticoOrigem");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Lesao", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("PreDiagnosticos");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Paciente", b =>
                {
                    b.Navigation("Lesoes");

                    b.Navigation("Tratamentos");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.ProfissionalDeSaude", b =>
                {
                    b.Navigation("Tratamentos");
                });

            modelBuilder.Entity("SuaPeleBackend.Models.Tratamento", b =>
                {
                    b.Navigation("Medicamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
